### PR TITLE
Bite 1788 - Quick Start Guide

### PR DESCRIPTION
**Pull request by bsomogyi**
- **What does the PR do?** *Provides an example to get up and running with EO quickly*
- **What automated testing exists for this change?** *None. Documentation changes.*
- **Is there documentation?** *Yes.  New [guide](https://github.com/pearsontechnology/environment-operator/blob/bite-1788/docs/Getting_Started.md) was added along with supporting content*
- **Any dependencies?** *None*
- [x] **Has the changelog been updated?** 

For those on the Pearson Bitesize team that would like to validate. On your cluster, execute the following which is now part of the new Quick Start GUide:

```
git clone https://github.com/pearsontechnology/environment-operator.git
cd environment-operator
git checkout bite-1788
cd example/sample_app
./run_example.sh
```

### CODE REVIEW

**Comment by w1lnx** [comment]
LGTM

**Comment by bsomogyi** [comment]
LGTM

**Comment by FlanBr-yopG** [comment]
LGTM

**Comment by w1lnx** [comment]
LGTM

**Comment by FlanBr-yopG** [comment]
I see your 125-line "small bug" and I still 
LGTM!

**Pull request merged**
