### PR TITLE
Bite 1713 - Add Requests/Limits for Container Deployments

### PR DESCRIPTION
**Pull request by bsomogyi**
- **What does the PR do?** *This PR is to add the ability to make requests in your manifest (environments.bitesize) file to specify the QoS class for you container deployments. For those on the Bitesize/Pearson team. The JIRA ticket is [BITE-1713](https://agile-jira.pearson.com/browse/BITE-1713)*
- **What automated testing exists for this change?** *environment.bitesize used for cluster_test.go was updated to include requests*
- **Is there documentation?** *Expanded [documentation](https://github.com/pearsontechnology/environment-operator/blob/bite-1713/docs/Environment_Config.md) to include details for contents of the manifest file. Look under the requests bullet to see how to achieve each k8s QoS class. *
- **Any dependencies?** *None*
- [x] **Has the changelog been updated?**

### CODE REVIEW

**Comment by bsomogyi** [comment]
I'm going to commit some changes in the morning to provide a default Guaranted QoS (1 CPU/2Gi RAM) in the chance that someone doesn't specify resource requirements for their service. This default can always be overriden by specifying a request in the manifest.

**Comment by cristian-radu** [comment]
It would be good if we could cover all possible QoS classes. :) 

I think that by setting default requests we loose the ability to schedule BestEffort pods. We should also support setting limits for a service (either now or at a later point) so that we can schedule Burstable pods too.

This would make the operator more flexible and less opinionated.

**Comment by bsomogyi** [comment]
@cristian-radu Added new tests and limits into the manifest (5acdec1).  It has maximum limit defaults for each service (can be overriden).  So, in regards to your comment, we will support Guaranteed or Burstable QoS Classes, but not BestEffort since we are going to require a limit be set for each pod whether that is the default of user specified.

**Comment by cristian-radu** [comment]
LGTM

**Comment by cristian-radu** [comment]
LGTM

**Pull request merged**
